# Dummy Dockerfile for pushing built and tested images
# FIXME: Remove this and update the workflows after this feature is
# implemented
# https://github.com/docker/build-push-action/issues/17
ARG IMAGE_NAME
ARG TAG_NAME

FROM ${IMAGE_NAME}:${TAG_NAME}
