FROM sslhep/rucio-client:main

LABEL maintainer Ilija Vukotic <ivukotic@uchicago.edu>

COPY run_heartbeats.sh /usr/local/sbin/
COPY heartbeat.py /usr/local/sbin/
COPY rucio.cfg /opt/rucio/etc/
# ENV X509_USER_PROXY=/etc/proxy/x509up
# ENV RUCIO_AUTH_TYPE=x509_proxy
# ENV RUCIO_ACCOUNT=ivukotic

CMD [ "/usr/local/sbin/run_heartbeats.sh" ]