apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: stashcache
  name: stashcache-chicago
  namespace: osg
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: stashcache
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: osg.chic.nrp.internet2.edu
      initContainers:
      - name: chowndata
        image: busybox
        command: ["sh", "-c", "chown -R 999:997 /data/stash"]
        volumeMounts:
        - name: datavol
          mountPath: /data/stash
      containers:
      - name: stashcache
        image: efajardo/prp-stashcache
        resources:
           limits:
              memory: 20Gi
           requests:
              memory: 18Gi
        #command: ["sh", "-c", "sleep infinity"]
        env:
        - name: LOCAL_CACHE_DIR
          value: /data/stash
        - name: SITENAME
          value: Chicago-Kubernetes-PRP
        - name: RAMSIZE
          value: 13g
        - name: REDIRECTOR
          value: osg.chic.nrp.internet2.edu:9004
        - name: XRDHTTPPORT
          value: "9001"    
        imagePullPolicy: Always
        volumeMounts:
        - name: hostcert
          mountPath: /etc/grid-security/hostcert.pem
        - name: hostkey
          mountPath: /etc/grid-security/hostkey.pem
        - name: config
          mountPath: /etc/xrootd
        - name: datavol
          mountPath: /data/stash
      volumes:
      - name : hostcert
        hostPath:
           path: /etc/grid-security/hostcert.pem
           type: File
      - name : hostkey
        hostPath:
           path: /etc/grid-security/hostkey.pem
           type: File
      - name: config
        configMap:
          name: stashcache
      - name: datavol
        hostPath:
          path: /tank/DATA
          type: Directory

