#!/bin/bash

# Stash Origins must have have this set to redirector.osgstorage.org,
# included in the stash-origin RPM packaging
if [[ -n $XC_LOCAL_REDIRECTORS ]] &&
       [[ $XC_IMAGE_NAME != 'stash-origin' ]]; then
    
    # Tell Supervisor to start up a cmsd process 
    cat <<EOF > /etc/supervisord.d/10-xcache-cmsd.conf
[program:xcache-cmsd]
command=/usr/bin/cmsd -c /etc/xrootd/xrootd-%(ENV_XC_IMAGE_NAME).cfg -k fifo -n %(ENV_XC_IMAGE_NAME) -k %(ENV_XC_NUM_LOGROTATE)s -s /var/run/xrootd/cmsd-%(ENV_XC_IMAGE_NAME).pid -l /var/log/xrootd/cmsd.log
user=xrootd
autorestart=true
environment=LD_PRELOAD=/usr/lib64/libtcmalloc.so,TCMALLOC_RELEASE_RATE=10
EOF

    # Configure XCache to point to the local redirector(s)
    # To specify redirector(s), users should set XC_LOCAL_REDIRECTORS
    # to a comma-delimited list of <FQDN>:<PORT> for each redirector
    XROOTD_CONFIG=/etc/xrootd/config.d/50-generated-cmsd.conf

    echo "# This file automatically generated by XCache container startup" > $XROOTD_CONFIG

    IFS=',' read -ra REDIRECTORS <<< "$XC_LOCAL_REDIRECTORS"
    for REDIR in "${REDIRECTORS[@]}"; do
        FQDN=${REDIR%%:*}
        PORT=${REDIR##*:}
        CONFIG_LINE="all.manager $FQDN+ $PORT"
        echo "Writing '$CONFIG_LINE' to /etc/xrootd/config.d/50-generated-cmsd.conf..."
        echo $CONFIG_LINE >> $XROOTD_CONFIG
    done
fi
